name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: kali-linux-latest

    env:
      REGISTRY: docker.io
      IMAGE_NAME: quvatovbaxtiyor/test_project

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Step 4: Build and push Docker images for each service
      - name: Build and push Admin Dashboard Backend
        uses: docker/build-push-action@v4
        with:
          context: ./admin_dashboard/backend
          file: ./admin_dashboard/backend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:admin_dashboard_backend-latest

      - name: Build and push Admin Dashboard Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./admin_dashboard/frontend
          file: ./admin_dashboard/frontend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:admin_dashboard_frontend-latest

      - name: Build and push API Service
        uses: docker/build-push-action@v4
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:api_service-latest

      - name: Build and push Main Website Backend
        uses: docker/build-push-action@v4
        with:
          context: ./main_website/backend
          file: ./main_website/backend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main_website_backend-latest

      - name: Build and push Main Website Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./main_website/frontend
          file: ./main_website/frontend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main_website_frontend-latest

      - name: Build and push Online Website Backend
        uses: docker/build-push-action@v4
        with:
          context: ./online_website/backend
          file: ./online_website/backend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:online_website_backend-latest

      - name: Build and push Online Website Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./online_website/frontend
          file: ./online_website/frontend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:online_website_frontend-latest

  deploy:
    name: Deploy Services
    runs-on: kali-linux-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        uses: docker/setup-qemu-action@v2

      - name: Deploy with Docker Compose
        run: |
          docker-compose down
          docker-compose up -d
